services:
  # local Azure storage account emulator
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
    volumes:
      - dask_azurite_volume:/data mcr.microsoft.com/azure-storage/azurite
    command: ["azurite-blob", "--blobHost", "0.0.0.0"]

  # Dask cluster: scheduler
  # Dask cluster: workers
  # TODO

volumes:
  dask_azurite_volume: {}
