services:
  # local Azure storage account emulator
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
    volumes:
      - dask_azurite_volume:/data mcr.microsoft.com/azure-storage/azurite
    command: ["azurite-blob", "--blobHost", "0.0.0.0"]

  dask_scheduler:
    image: ghcr.io/dask/dask
    container_name: scheduler
    ports:
      - 8787:8787 # dashboard
      - 8786:8786 # task API
    command: ["dask-scheduler"]

  dask_worker1: &dask-worker
    image: ghcr.io/dask/dask
    command: ["dask-worker", "scheduler:8786", "--host", "0.0.0.0"]

  dask_worker2:
    <<: *dask-worker

  dask_worker3:
    <<: *dask-worker

volumes:
  dask_azurite_volume: {}
