x-dask-common: &dask-common
  image: dask-base
  build: .

x-dask_worker: &dask-worker
  <<: *dask-common
  depends_on:
    - dask_scheduler
  command: ["dask-worker", "scheduler:8786", "--host", "0.0.0.0"]

services:
  # local Azure storage account emulator
  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
    volumes:
      - ./azurite/data:/data
      - ./azurite/cert:/cert
    command:
      [
        "azurite-blob",
        "--oauth",
        "basic",
        "--location",
        "/data",
        "--blobHost",
        "0.0.0.0",
        "--cert",
        "/cert/cert.pem",
        "--key",
        "/cert/key.pem",
      ]

  # dev_notebook:
  #   <<: *dask-common
  #   ports:
  #     - 8888:8888
  #   working_dir: /work
  #   volumes:
  #     - ./:/work
  #   command:
  #     [
  #       "jupyter",
  #       "notebook",
  #       "-y",
  #       "--no-browser",
  #       "--allow-root",
  #       "--port=8888",
  #       "--ip=0.0.0.0",
  #     ]

  dask_scheduler:
    <<: *dask-common
    container_name: scheduler
    ports:
      - 8787:8787 # dashboard
    command: ["dask-scheduler"]

  dask_worker1:
    <<: *dask-worker

  dask_worker2:
    <<: *dask-worker

  dask_worker3:
    <<: *dask-worker
